sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hbAXFIa94owBMqta/9gzzhJsJYbx//QUCPy3MjiD6YhScAftmZgmQjaUc4KhBo9R33D9BlpBpVDQxd3qQNikzQ9r45f8YBvlNSchpzvhCu0h3BY7Xbd8mnVXZA2cXi8lCGvQRVf6gnTiOOaICBz+b1mkaC+VpEYARoDgX1BWM2XE7Gw1f4SYU/JIoYd/SiyCz/T4XyiFOQYNX5PXVnmBMF8YAhT951FO6Id4S2OErTPJgSPBTns4xXpEO46iSxNDQqMMeKnZa1Df9K35qLf3vlevU0q83Txr3SNO5LYc9lmsmH1QmQ3q9LBsNJt22HTlP/7YCWj2jbKSnQ4jJ9GQxmArLQGfKYfnIxsY8TebfjrZP1McK6q8V2WjFNXiGhPaNJMYF+4SOG1wly3OAvtRrqgkrcwclfJ7o6NM9TUyZu4oFOGO/KlmeDFxs9oUDAOUSrO+T1iVxMEsKruh/iClCn8WqIw4twkYH2I/LpujQKvkQRsgR82KF+WJ39B4eoKgaJ7SeMXuuQCYrgfwrOB7i/bcfQaBa+uf8rbLXpNcWWEjBFLu7q1Gn2Sz/LOL/OM2QdIQx3OH0CB1vuBN+GLYFbiNZFoqtvJVTuN5GDeOTytsn2KTUPcPBRyK61xf5ZLqo/NJvyKOA5YLP4lwW5Rfgn+KIz4syY9KQ8q/St6TLes=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Madame-Chrysantheme-Volume-2_3992
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy